/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/advance_components_paterns': RouteRecordInfo<'/advance_components_paterns', '/advance_components_paterns', Record<never, never>, Record<never, never>>,
    '/class_&_style_binding': RouteRecordInfo<'/class_&_style_binding', '/class_&_style_binding', Record<never, never>, Record<never, never>>,
    '/excercise': RouteRecordInfo<'/excercise', '/excercise', Record<never, never>, Record<never, never>>,
    '/excercise_ref_components_dataBinding': RouteRecordInfo<'/excercise_ref_components_dataBinding', '/excercise_ref_components_dataBinding', Record<never, never>, Record<never, never>>,
    '/Homepage': RouteRecordInfo<'/Homepage', '/Homepage', Record<never, never>, Record<never, never>>,
    '/learnAxios': RouteRecordInfo<'/learnAxios', '/learnAxios', Record<never, never>, Record<never, never>>,
    '/ref_components_dataBinding': RouteRecordInfo<'/ref_components_dataBinding', '/ref_components_dataBinding', Record<never, never>, Record<never, never>>,
    '/reusability_composable': RouteRecordInfo<'/reusability_composable', '/reusability_composable', Record<never, never>, Record<never, never>>,
    '/storrr': RouteRecordInfo<'/storrr', '/storrr', Record<never, never>, Record<never, never>>,
    '/try': RouteRecordInfo<'/try', '/try', Record<never, never>, Record<never, never>>,
  }
}
